version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8019:8000'
    environment:
      - PYTHONUNBUFFERED=1
      - API_KEY=sk-6zvekr4931xm
      - FILE_SERVER_URL=http://10.120.120.6:3008
    command: python api.py
