-- AlterTable
ALTER TABLE "iocard_selection" ALTER COLUMN "supportsCAN20A_B" DROP DEFAULT,
ALTER COLUMN "supportsRS232" DROP DEFAULT,
ALTER COLUMN "supportsRS422" DROP DEFAULT,
ALTER COLUMN "supportsRS485" DROP DEFAULT;
